version: "3.9"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        environment:
            NODE_ENV: development
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: gestair
            MYSQL_DATABASE: gestair
            MYSQL_USER: gestair
            MYSQL_PASSWORD: gestair

volumes:
    mysql_data: {}
