version: "3.9"

services:
    app:
        build: .
        container_name: "app"
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
            port: 3000
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: "mysql8"
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        cap_add: 
            - SYS_NICE
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gestair
            MYSQL_USER: gestair
            MYSQL_PASSWORD: gestair
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
    mysql_data: {}
